name: Deploy to VIX Futures Lambdas

on:
  push:
    branches:
      - main
    paths:
      - "vix-futures/**"

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-lambda.yml
    with:
      lambda_functions: '["vix-futures-api","vix-futures-cboe"]'
      lambda_path: "vix-futures"
    secrets: inherit