name: Deploy to VIX Futures API

on:
  push:
    branches:
      - main
    paths:
      - "vix-futures/**"

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-lambda.yml
    with:
      lambda_name: "vix-futures-api"
      lambda_path: "vix-futures"
    secrets: inherit